### ISSUE TITLE
createFriendRequest.php

### ISSUE THREAD

**Issue by aml35** [jasperdavey/CS490Project#46]
jasper when I run createFriendRequest.php I qet back 200
but pendingFriendRequest does not get updated 

I tried then to acceptFriendRequest and got back 404

**Comment by jasperdavey** [comment]
This is possibly due to either one of the users not existing. So far there are only 1,2,3,9 users in the database. You could also get 404 if the users are already friends. For accuracy, create 2 new users and try to name them friends. Just ran my tests and it's working properly. I made user 9 ask user 3 to be friends and pendingFriendRequests for user 3 received 9. I then ran acceptFriendRequest and user 9 was added to user 3's friends list and user 3 was added user 9's friend list.
