### ISSUE TITLE
get friends events not working 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#59]
sending -- 'command=13&id=3'

getting this back
{"status":200,"info":[[""],[""]]}

if have 2 friends in my profile 
{"status":200,"info":{"id":"3","email":"tr88@njit.edu","username":"tr88","firstname":"Devin","lastname":"Ramrattan","bio":"EAT SLEEP CODE !!!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"1,2","pendingFriendRequests":"","createdEvents":"3","tags":[{"id":"7","owner":"3","tag":"#CS","nice":"0","type":"0"},{"id":"8","owner":"3","tag":"#ComputerScience","nice":"0","type":"0"}]}}

**Comment by aml35** [comment]
{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg",**"events":""**,"friends":"3","pendingFriendRequests":"3","createdEvents":"4","tags":[{"id":"12","owner":"1","tag":"#CS","nice":"1","type":"0"},{"id":"13","owner":"1","tag":"#Software","nice":"1","type":"0"}]}}

{"status":200,"info":{"id":"2","email":"test@njit.edu","username":"Bobby","firstname":"Bob","lastname":"Saget","bio":"I hate CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg",**"events":""**,"friends":"3","pendingFriendRequests":"3","createdEvents":"2","tags":[]}}

your friends have "events": "" 

that's why you get {"status":200,"info":[[""],[""]]}

**Comment by aml35** [comment]
**Here is Jasper's code:**

foreach ( $userFriends as $singleFriend )
    {
        $sql = sprintf( "SELECT \* FROM Users WHERE id = '%s'", mysql_real_escape_string( $singleFriend ) );
        $friend = mysql_query( $sql, $connection );
        if ( !$friend )
        {
            $message = 'Invalid query: ' . mysql_error( ) . "\n";
            $message .= 'Whole query: ' . $sql;
            print( $message );
            $status = 404;
            reportBack( $status, $info = "NULL" );
        }
        while ( $row = mysql_fetch_assoc( $friend ) )
        {
            array_push( $userFriendsArray, explode( ",", $row[ 'events' ] ) );
        }
    }
