### ISSUE TITLE
pendingFriendRequest does not get updated after acceptance 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#62]
test it with two users

**Comment by jasperdavey** [comment]
I tested this and it's working correctly on my end. I do see user 4, the pendingFriendRequest of 1 is still there. This could be due to another call to pendingFriendRequest from user 1 to user 4 after the acceptance.

**Comment by jasperdavey** [comment]
Looking further, this is actually impossible as my code has a way to prevent this. Investigating.

**Comment by jasperdavey** [comment]
Unable to reproduce. Please provide steps of reproduction.

**Comment by aml35** [comment]
{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1,2"**,"friends":"3,4,5,6"**,**"pendingFriendRequests":"3"**,"createdEvents":"2,5,6,13","tags":[{"id":"12","owner":"1","tag":"#CS","nice":"1","type":"0"},{"id":"13","owner":"1","tag":"#Software","nice":"1","type":"0"}]}}

I think the issue is when creating a friendRequest jasper only checks if  exist already a pending request with the targetID but do not check if the initiatorID and the tagetID are already friends.

In the above example 1 and 3 are friends but another request was sent by user 3 to 1 again and it was not rejected. therefore, you see a pending request from user 3

**Comment by jasperdavey** [comment]
I've tried to reproduce this again but I simply cannot. I get back {"status":304} which is what it's designed to do. in createFriendRequest.php i wrote:

``` php
// Check if initiatorID already has requested this person
    if ( in_array( $result->initiatorID, $friendlist ) || in_array( $result->initiatorID, $pendingFriendRequests ) )
    {
        $status = 304;
        reportBack( $status );
    }
```

There must be some sort of edge case that is being implemented but I can't find it if I can't reproduce. Either that or the bug got fixed between the time it was discovered till now. I think it's best to simply ignore this unless it happens again on a new user.
